using System.Diagnostics;
using System.Globalization;
using System.Runtime.InteropServices;
using Microsoft.Win32;

// Convert typical interpolated strings to use composite formatting for better language accuracy.

namespace uhla.Core {
    namespace Language {
        internal enum Languages {
            Null,               // Used for unrecognized language specify from terminal

            English_UK,
            English_US,
            Spanish,
            German,
            Japanese,
            French,
            Portuguese,
            Russian,
            Italian,
            Dutch,
            Polish,
            Turkish,
            Vietnamese,
            Indonesian,
            Czech,
            Korean,
            Ukrainian,
            Arabic,
            Swedish,
            Persian,
            Chinese
        }

        internal class Language {
            // Note : Operating Systems that wont return en_us/en_gb will be forced to use UK English.
            //        The way I see it, its either enforce UK or enforce US. This way people might be inclined to ask about the projects origins.
            // Generated Method:
            internal static Languages CaptureSystemLanguage() {
                string langCode;
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
                    using var key   = Registry.CurrentUser.OpenSubKey(@"Control Panel\International\User Profile");
                    var       langs = key?.GetValue("Languages") as string[];
                    langCode = langs?.FirstOrDefault() ?? CultureInfo.InstalledUICulture.Name;
                } else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
                    langCode = Environment.GetEnvironmentVariable("LANG")?
                       .Split('.')[0] ?? "en";
                } else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) {
                    var psi = new ProcessStartInfo("defaults", "read .GlobalPreferences AppleLanguages") {
                        RedirectStandardOutput = true
                    };
                    var outp = Process.Start(psi)!.StandardOutput.ReadToEnd();
                    langCode = outp.Split(['"', ','], StringSplitOptions.RemoveEmptyEntries)
                                   .FirstOrDefault(s => s.Length >= 2) ?? "en";
                } else {
                    // error, attempted to capture system language
                    langCode = "";
                }

                return langCode switch {
                    "en" or "en-GB"            => Languages.English_UK,
                    "en-US"                    => Languages.English_US,
                    "es" or "es-ES"            => Languages.Spanish,
                    "de" or "de-DE"            => Languages.German,
                    "ja" or "ja-JP"            => Languages.Japanese,
                    "fr" or "fr-FR"            => Languages.French,
                    "pt" or "pt-PT" or "pt-BR" => Languages.Portuguese,
                    "ru" or "ru-RU"            => Languages.Russian,
                    "it" or "it-IT"            => Languages.Italian,
                    "nl" or "nl-NL"            => Languages.Dutch,
                    "pl" or "pl-PL"            => Languages.Polish,
                    "tr" or "tr-TR"            => Languages.Turkish,
                    "vi" or "vi-VN"            => Languages.Vietnamese,
                    "id" or "id-ID"            => Languages.Indonesian,
                    "cs" or "cs-CZ"            => Languages.Czech,
                    "ko" or "ko-KR"            => Languages.Korean,
                    "uk" or "uk-UA"            => Languages.Ukrainian,
                    "ar" or "ar-SA"            => Languages.Arabic,
                    "sv" or "sv-SE"            => Languages.Swedish,
                    "fa" or "fa-IR"            => Languages.Persian,
                    "zh" or "zh-CN" or "zh-TW" => Languages.Chinese,
                    _                          => Languages.English_US
                };
            }

            internal static readonly Dictionary<(Languages, ErrorNames), Func<object[], string>> Errors = new() {
                // Linker
                // erroneous top level segments
                {(Languages.English_UK, ErrorNames.ErroneousTopLevelSegment), (object[] args) => string.Format("Erroneous table '{0}' found at the top level of linker script, may only consist of 'static', 'dynamic' and 'rules'", args)}
            };

        /// <summary>
            /// Here, connectives refer to strings that connect translated components that directly describe the context of the information.
            /// </summary>
            internal static readonly Dictionary<(Languages, string), string> Connectives = new() {
                // During
                {(Languages.English_UK, "During"), "During"},
                {(Languages.English_US, "During"), "During"},
                {(Languages.Spanish,    "During"), "Durante"},
                {(Languages.German,     "During"), "Während"},
                {(Languages.French,     "During"), "Pendant"},
                {(Languages.Portuguese, "During"), "Durante"},
                {(Languages.Russian,    "During"), "Во время"},
                {(Languages.Italian,    "During"), "Durante"},
                {(Languages.Dutch,      "During"), "Tijdens"},
                {(Languages.Polish,     "During"), "Podczas"},
                {(Languages.Turkish,    "During"), "Sırasında"},
                {(Languages.Vietnamese, "During"), "Trong lúc"},
                {(Languages.Indonesian, "During"), "Selama"},
                {(Languages.Czech,      "During"), "Během"},
                {(Languages.Korean,     "During"), "동안"},
                {(Languages.Ukrainian,  "During"), "Під час"},
                {(Languages.Arabic,     "During"), "أثناء"},
                {(Languages.Swedish,    "During"), "Under"},
                {(Languages.Persian,    "During"), "در طول"},
                {(Languages.Chinese,    "During"), "在…期间"},

                // Could not Fetch Required Context from
                {(Languages.English_UK, "Could not Fetch Required Context from"), "Could not Fetch Required Context from"},
                {(Languages.English_US, "Could not Fetch Required Context from"), "Could not Fetch Required Context from"},
                {(Languages.Spanish,    "Could not Fetch Required Context from"), "No se pudo obtener el contexto requerido desde"},
                {(Languages.German,     "Could not Fetch Required Context from"), "Konnte den erforderlichen Kontext nicht abrufen von"},
                {(Languages.French,     "Could not Fetch Required Context from"), "Impossible de récupérer le contexte requis de"},
                {(Languages.Portuguese, "Could not Fetch Required Context from"), "Não foi possível obter o contexto necessário de"},
                {(Languages.Russian,    "Could not Fetch Required Context from"), "Не удалось получить требуемый контекст из"},
                {(Languages.Italian,    "Could not Fetch Required Context from"), "Impossibile recuperare il contesto richiesto da"},
                {(Languages.Dutch,      "Could not Fetch Required Context from"), "Kan de vereiste context niet ophalen van"},
                {(Languages.Polish,     "Could not Fetch Required Context from"), "Nie można pobrać wymaganego kontekstu z"},
                {(Languages.Turkish,    "Could not Fetch Required Context from"), "Gerekli bağlam alınamadı - kaynak:"},
                {(Languages.Vietnamese, "Could not Fetch Required Context from"), "Không thể lấy ngữ cảnh cần thiết từ"},
                {(Languages.Indonesian, "Could not Fetch Required Context from"), "Tidak dapat mengambil konteks yang diperlukan dari"},
                {(Languages.Czech,      "Could not Fetch Required Context from"), "Nelze načíst požadovaný kontext z"},
                {(Languages.Korean,     "Could not Fetch Required Context from"), "필요한 컨텍스트를 다음에서 가져올 수 없습니다:"},
                {(Languages.Ukrainian,  "Could not Fetch Required Context from"), "Не вдалося отримати потрібний контекст з"},
                {(Languages.Arabic,     "Could not Fetch Required Context from"), "تعذّر جلب السياق المطلوب من"},
                {(Languages.Swedish,    "Could not Fetch Required Context from"), "Kunde inte hämta nödvändig kontext från"},
                {(Languages.Persian,    "Could not Fetch Required Context from"), "امکان واکشی زمینه لازم از وجود ندارد"},
                {(Languages.Chinese,    "Could not Fetch Required Context from"), "无法从…获取所需的上下文"},

                // Unexpected Line Termination in
                {(Languages.English_UK, "Unexpected Line Termination in"), "Unexpected Line Termination in"},
                {(Languages.English_US, "Unexpected Line Termination in"), "Unexpected Line Termination in"},
                {(Languages.Spanish,    "Unexpected Line Termination in"), "Terminación inesperada de línea en"},
                {(Languages.German,     "Unexpected Line Termination in"), "Unerwartetes Zeilenende in"},
                {(Languages.French,     "Unexpected Line Termination in"), "Fin de ligne inattendue dans"},
                {(Languages.Portuguese, "Unexpected Line Termination in"), "Término de linha inesperado em"},
                {(Languages.Russian,    "Unexpected Line Termination in"), "Неожиданное окончание строки в"},
                {(Languages.Italian,    "Unexpected Line Termination in"), "Terminazione di linea imprevista in"},
                {(Languages.Dutch,      "Unexpected Line Termination in"), "Onverwachte regeleinde in"},
                {(Languages.Polish,     "Unexpected Line Termination in"), "Nieoczekiwane zakończenie wiersza w"},
                {(Languages.Turkish,    "Unexpected Line Termination in"), "Beklenmeyen satır sonu içinde"},
                {(Languages.Vietnamese, "Unexpected Line Termination in"), "Kết thúc dòng không mong muốn trong"},
                {(Languages.Indonesian, "Unexpected Line Termination in"), "Penghentian baris tak terduga di"},
                {(Languages.Czech,      "Unexpected Line Termination in"), "Neočekávané ukončení řádku v"},
                {(Languages.Korean,     "Unexpected Line Termination in"), "예기치 않은 줄 끝남 발생 위치:"},
                {(Languages.Ukrainian,  "Unexpected Line Termination in"), "Несподіване завершення рядка в"},
                {(Languages.Arabic,     "Unexpected Line Termination in"), "إنهاء السطر غير المتوقع في"},
                {(Languages.Swedish,    "Unexpected Line Termination in"), "Oväntat radslut i"},
                {(Languages.Persian,    "Unexpected Line Termination in"), "پایان خط غیرمنتظره در"},
                {(Languages.Chinese,    "Unexpected Line Termination in"), "在…中意外的行终止"},

                // Source file
                {(Languages.English_UK, "Source file"), "Source file"},
                {(Languages.English_US, "Source file"), "Source file"},
                {(Languages.Spanish,    "Source file"), "Archivo fuente"},
                {(Languages.German,     "Source file"), "Quelldatei"},
                {(Languages.French,     "Source file"), "Fichier source"},
                {(Languages.Portuguese, "Source file"), "Arquivo fonte"},
                {(Languages.Russian,    "Source file"), "Исходный файл"},
                {(Languages.Italian,    "Source file"), "File sorgente"},
                {(Languages.Dutch,      "Source file"), "Bronbestand"},
                {(Languages.Polish,     "Source file"), "Plik źródłowy"},
                {(Languages.Turkish,    "Source file"), "Kaynak dosya"},
                {(Languages.Vietnamese, "Source file"), "Tệp nguồn"},
                {(Languages.Indonesian, "Source file"), "Berkas sumber"},
                {(Languages.Czech,      "Source file"), "Zdrojový soubor"},
                {(Languages.Korean,     "Source file"), "소스 파일"},
                {(Languages.Ukrainian,  "Source file"), "Файловий файл"},
                {(Languages.Arabic,     "Source file"), "ملف المصدر"},
                {(Languages.Swedish,    "Source file"), "Källfil"},
                {(Languages.Persian,    "Source file"), "فایل منبع"},
                {(Languages.Chinese,    "Source file"), "源文件"},

                // has no contents
                {(Languages.English_UK, "has no contents"), "has no contents"},
                {(Languages.English_US, "has no contents"), "has no contents"},
                {(Languages.Spanish,    "has no contents"), "no tiene contenido"},
                {(Languages.German,     "has no contents"), "hat keinen Inhalt"},
                {(Languages.French,     "has no contents"), "n’a pas de contenu"},
                {(Languages.Portuguese, "has no contents"), "não tem conteúdo"},
                {(Languages.Russian,    "has no contents"), "не содержит данных"},
                {(Languages.Italian,    "has no contents"), "non ha contenuto"},
                {(Languages.Dutch,      "has no contents"), "heeft geen inhoud"},
                {(Languages.Polish,     "has no contents"), "nie zawiera treści"},
                {(Languages.Turkish,    "has no contents"), "içerik yok"},
                {(Languages.Vietnamese, "has no contents"), "không có nội dung"},
                {(Languages.Indonesian, "has no contents"), "tidak memiliki konten"},
                {(Languages.Czech,      "has no contents"), "nemá obsah"},
                {(Languages.Korean,     "has no contents"), "내용이 없습니다"},
                {(Languages.Ukrainian,  "has no contents"), "не містить вмісту"},
                {(Languages.Arabic,     "has no contents"), "لا يحتوي على محتوى"},
                {(Languages.Swedish,    "has no contents"), "har inget innehåll"},
                {(Languages.Persian,    "has no contents"), "محتوا ندارد"},
                {(Languages.Chinese,    "has no contents"), "没有内容"},

                // Input path must be provided
                {(Languages.English_UK, "Input path must be provided"), "Input path must be provided"},
                {(Languages.English_US, "Input path must be provided"), "Input path must be provided"},
                {(Languages.Spanish,    "Input path must be provided"), "Se debe proporcionar la ruta de entrada"},
                {(Languages.German,     "Input path must be provided"), "Eingabepfad muss angegeben werden"},
                {(Languages.French,     "Input path must be provided"), "Le chemin d'entrée doit être fourni"},
                {(Languages.Portuguese, "Input path must be provided"), "O caminho de entrada deve ser fornecido"},
                {(Languages.Russian,    "Input path must be provided"), "Необходимо указать путь к входному файлу"},
                {(Languages.Italian,    "Input path must be provided"), "Il percorso di input deve essere fornito"},
                {(Languages.Dutch,      "Input path must be provided"), "Invoepad moet worden opgegeven"},
                {(Languages.Polish,     "Input path must be provided"), "Należy podać ścieżkę wejściową"},
                {(Languages.Turkish,    "Input path must be provided"), "Girdi yolu sağlanmalıdır"},
                {(Languages.Vietnamese, "Input path must be provided"), "Phải cung cấp đường dẫn đầu vào"},
                {(Languages.Indonesian, "Input path must be provided"), "Jalur input harus disediakan"},
                {(Languages.Czech,      "Input path must be provided"), "Musí být zadána vstupní cesta"},
                {(Languages.Korean,     "Input path must be provided"), "입력 경로를 제공해야 합니다"},
                {(Languages.Ukrainian,  "Input path must be provided"), "Потрібно вказати шлях до вхідного файлу"},
                {(Languages.Arabic,     "Input path must be provided"), "يجب تقديم مسار الإدخال"},
                {(Languages.Swedish,    "Input path must be provided"), "Inmatningssökväg måste anges"},
                {(Languages.Persian,    "Input path must be provided"), "مسیر ورودی باید ارائه شود"},
                {(Languages.Chinese,    "Input path must be provided"), "必须提供输入路径"},

                // Output path must be provided
                {(Languages.English_UK, "Output path must be provided"), "Output path must be provided"},
                {(Languages.English_US, "Output path must be provided"), "Output path must be provided"},
                {(Languages.Spanish,    "Output path must be provided"), "Se debe proporcionar la ruta de salida"},
                {(Languages.German,     "Output path must be provided"), "Ausgabepfad muss angegeben werden"},
                {(Languages.French,     "Output path must be provided"), "Le chemin de sortie doit être fourni"},
                {(Languages.Portuguese, "Output path must be provided"), "O caminho de saída deve ser fornecido"},
                {(Languages.Russian,    "Output path must be provided"), "Необходимо указать путь к выходному файлу"},
                {(Languages.Italian,    "Output path must be provided"), "Il percorso di output deve essere fornito"},
                {(Languages.Dutch,      "Output path must be provided"), "Uitvoepad moet worden opgegeven"},
                {(Languages.Polish,     "Output path must be provided"), "Należy podać ścieżkę wyjściową"},
                {(Languages.Turkish,    "Output path must be provided"), "Çıktı yolu sağlanmalıdır"},
                {(Languages.Vietnamese, "Output path must be provided"), "Phải cung cấp đường dẫn đầu ra"},
                {(Languages.Indonesian, "Output path must be provided"), "Jalur output harus disediakan"},
                {(Languages.Czech,      "Output path must be provided"), "Musí být zadána výstupní cesta"},
                {(Languages.Korean,     "Output path must be provided"), "출력 경로를 제공해야 합니다"},
                {(Languages.Ukrainian,  "Output path must be provided"), "Потрібно вказати шлях до вихідного файлу"},
                {(Languages.Arabic,     "Output path must be provided"), "يجب تقديم مسار الإخراج"},
                {(Languages.Swedish,    "Output path must be provided"), "Utmatningssökväg måste anges"},
                {(Languages.Persian,    "Output path must be provided"), "مسیر خروجی باید ارائه شود"},
                {(Languages.Chinese,    "Output path must be provided"), "必须提供输出路径"},

                // No Input Path Provided
                {(Languages.English_UK, "No Input Path Provided"), "No Input Path Provided"},
                {(Languages.English_US, "No Input Path Provided"), "No Input Path Provided"},
                {(Languages.Spanish,    "No Input Path Provided"), "No se proporcionó la ruta de entrada"},
                {(Languages.German,     "No Input Path Provided"), "Kein Eingabepfad angegeben"},
                {(Languages.French,     "No Input Path Provided"), "Aucun chemin d'entrée fourni"},
                {(Languages.Portuguese, "No Input Path Provided"), "Nenhum caminho de entrada fornecido"},
                {(Languages.Russian,    "No Input Path Provided"), "Путь к входному файлу не указан"},
                {(Languages.Italian,    "No Input Path Provided"), "Nessun percorso di input fornito"},
                {(Languages.Dutch,      "No Input Path Provided"), "Geen invoepad opgegeven"},
                {(Languages.Polish,     "No Input Path Provided"), "Nie podano ścieżki wejściowej"},
                {(Languages.Turkish,    "No Input Path Provided"), "Girdi yolu sağlanmadı"},
                {(Languages.Vietnamese, "No Input Path Provided"), "Không cung cấp đường dẫn đầu vào"},
                {(Languages.Indonesian, "No Input Path Provided"), "Jalur input tidak disediakan"},
                {(Languages.Czech,      "No Input Path Provided"), "Nebyla zadána vstupní cesta"},
                {(Languages.Korean,     "No Input Path Provided"), "입력 경로가 제공되지 않았습니다"},
                {(Languages.Ukrainian,  "No Input Path Provided"), "Шлях до вхідного файлу не вказано"},
                {(Languages.Arabic,     "No Input Path Provided"), "لم يتم تقديم مسار الإدخال"},
                {(Languages.Swedish,    "No Input Path Provided"), "Ingen inmatningssökväg angiven"},
                {(Languages.Persian,    "No Input Path Provided"), "مسیر ورودی ارائه نشده است"},
                {(Languages.Chinese,    "No Input Path Provided"), "未提供输入路径"},

                // Input Source File Path has already been specified
                {(Languages.English_UK, "Input Source File Path has already been specified"), "Input Source File Path has already been specified"},
                {(Languages.English_US, "Input Source File Path has already been specified"), "Input Source File Path has already been specified"},
                {(Languages.Spanish,    "Input Source File Path has already been specified"), "La ruta del archivo de entrada ya ha sido especificada"},
                {(Languages.German,     "Input Source File Path has already been specified"), "Pfad zur Eingabedatei wurde bereits angegeben"},
                {(Languages.French,     "Input Source File Path has already been specified"), "Le chemin du fichier source a déjà été spécifié"},
                {(Languages.Portuguese, "Input Source File Path has already been specified"), "O caminho do arquivo de entrada já foi especificado"},
                {(Languages.Russian,    "Input Source File Path has already been specified"), "Путь к входному файлу уже указан"},
                {(Languages.Italian,    "Input Source File Path has already been specified"), "Il percorso del file di input è già stato specificato"},
                {(Languages.Dutch,      "Input Source File Path has already been specified"), "Pad naar invoerbestand is al opgegeven"},
                {(Languages.Polish,     "Input Source File Path has already been specified"), "Ścieżka do pliku wejściowego została już określona"},
                {(Languages.Turkish,    "Input Source File Path has already been specified"), "Giriş dosyası yolu zaten belirtilmiş"},
                {(Languages.Vietnamese, "Input Source File Path has already been specified"), "Đường dẫn tệp nguồn đầu vào đã được chỉ định"},
                {(Languages.Indonesian, "Input Source File Path has already been specified"), "Jalur file input sudah ditentukan"},
                {(Languages.Czech,      "Input Source File Path has already been specified"), "Cesta ke vstupnímu souboru již byla zadána"},
                {(Languages.Korean,     "Input Source File Path has already been specified"), "입력 소스 파일 경로가 이미 지정되었습니다"},
                {(Languages.Ukrainian,  "Input Source File Path has already been specified"), "Шлях до вхідного файлу вже вказано"},
                {(Languages.Arabic,     "Input Source File Path has already been specified"), "تم تحديد مسار ملف الإدخال بالفعل"},
                {(Languages.Swedish,    "Input Source File Path has already been specified"), "Sökväg till indatafilen har redan angetts"},
                {(Languages.Persian,    "Input Source File Path has already been specified"), "مسیر فایل ورودی قبلاً مشخص شده است"},
                {(Languages.Chinese,    "Input Source File Path has already been specified"), "输入源文件路径已被指定"},

                // No Output Path Provided
                {(Languages.English_UK, "No Output Path Provided"), "No Output Path Provided"},
                {(Languages.English_US, "No Output Path Provided"), "No Output Path Provided"},
                {(Languages.Spanish,    "No Output Path Provided"), "No se proporcionó la ruta de salida"},
                {(Languages.German,     "No Output Path Provided"), "Kein Ausgabepfad angegeben"},
                {(Languages.French,     "No Output Path Provided"), "Aucun chemin de sortie fourni"},
                {(Languages.Portuguese, "No Output Path Provided"), "Nenhum caminho de saída fornecido"},
                {(Languages.Russian,    "No Output Path Provided"), "Путь к выходному файлу не указан"},
                {(Languages.Italian,    "No Output Path Provided"), "Nessun percorso di output fornito"},
                {(Languages.Dutch,      "No Output Path Provided"), "Geen uitvoerpad opgegeven"},
                {(Languages.Polish,     "No Output Path Provided"), "Nie podano ścieżki wyjściowej"},
                {(Languages.Turkish,    "No Output Path Provided"), "Çıkış yolu sağlanmadı"},
                {(Languages.Vietnamese, "No Output Path Provided"), "Không cung cấp đường dẫn đầu ra"},
                {(Languages.Indonesian, "No Output Path Provided"), "Jalur output tidak disediakan"},
                {(Languages.Czech,      "No Output Path Provided"), "Nebyla zadána výstupní cesta"},
                {(Languages.Korean,     "No Output Path Provided"), "출력 경로가 제공되지 않았습니다"},
                {(Languages.Ukrainian,  "No Output Path Provided"), "Шлях до вихідного файлу не вказано"},
                {(Languages.Arabic,     "No Output Path Provided"), "لم يتم تقديم مسار الإخراج"},
                {(Languages.Swedish,    "No Output Path Provided"), "Ingen utmatningssökväg angiven"},
                {(Languages.Persian,    "No Output Path Provided"), "مسیر خروجی ارائه نشده است"},
                {(Languages.Chinese,    "No Output Path Provided"), "未提供输出路径"},

                // Output Binary File Path has already been specified
                {(Languages.English_UK, "Output Binary File Path has already been specified"), "Output Binary File Path has already been specified"},
                {(Languages.English_US, "Output Binary File Path has already been specified"), "Output Binary File Path has already been specified"},
                {(Languages.Spanish,    "Output Binary File Path has already been specified"), "La ruta del archivo binario de salida ya ha sido especificada"},
                {(Languages.German,     "Output Binary File Path has already been specified"), "Pfad zur Ausgabedatei wurde bereits angegeben"},
                {(Languages.French,     "Output Binary File Path has already been specified"), "Le chemin du fichier binaire de sortie a déjà été spécifié"},
                {(Languages.Portuguese, "Output Binary File Path has already been specified"), "O caminho do arquivo binário de saída já foi especificado"},
                {(Languages.Russian,    "Output Binary File Path has already been specified"), "Путь к выходному файлу уже указан"},
                {(Languages.Italian,    "Output Binary File Path has already been specified"), "Il percorso del file binario di output è già stato specificato"},
                {(Languages.Dutch,      "Output Binary File Path has already been specified"), "Pad naar uitvoerbestand is al opgegeven"},
                {(Languages.Polish,     "Output Binary File Path has already been specified"), "Ścieżka do pliku wyjściowego została już określona"},
                {(Languages.Turkish,    "Output Binary File Path has already been specified"), "Çıkış dosyası yolu zaten belirtilmiş"},
                {(Languages.Vietnamese, "Output Binary File Path has already been specified"), "Đường dẫn tệp nhị phân đầu ra đã được chỉ định"},
                {(Languages.Indonesian, "Output Binary File Path has already been specified"), "Jalur file output sudah ditentukan"},
                {(Languages.Czech,      "Output Binary File Path has already been specified"), "Cesta k výstupnímu souboru již byla zadána"},
                {(Languages.Korean,     "Output Binary File Path has already been specified"), "출력 바이너리 파일 경로가 이미 지정되었습니다"},
                {(Languages.Ukrainian,  "Output Binary File Path has already been specified"), "Шлях до вихідного файлу вже вказано"},
                {(Languages.Arabic,     "Output Binary File Path has already been specified"), "تم تحديد مسار ملف الإخراج الثنائي بالفعل"},
                {(Languages.Swedish,    "Output Binary File Path has already been specified"), "Sökväg till utdatafilen har redan angetts"},
                {(Languages.Persian,    "Output Binary File Path has already been specified"), "مسیر فایل خروجی قبلاً مشخص شده است"},
                {(Languages.Chinese,    "Output Binary File Path has already been specified"), "输出二进制文件路径已被指定"},

                // Unrecognized Terminal Argument
                {(Languages.English_UK, "Unrecognized Terminal Argument"), "Unrecognized Terminal Argument"},
                {(Languages.English_US, "Unrecognized Terminal Argument"), "Unrecognized Terminal Argument"},
                {(Languages.Spanish,    "Unrecognized Terminal Argument"), "Argumento de terminal no reconocido"},
                {(Languages.German,     "Unrecognized Terminal Argument"), "Nicht erkannter Terminal-Parameter"},
                {(Languages.French,     "Unrecognized Terminal Argument"), "Argument de terminal non reconnu"},
                {(Languages.Portuguese, "Unrecognized Terminal Argument"), "Argumento de terminal não reconhecido"},
                {(Languages.Russian,    "Unrecognized Terminal Argument"), "Неизвестный аргумент терминала"},
                {(Languages.Italian,    "Unrecognized Terminal Argument"), "Argomento del terminale non riconosciuto"},
                {(Languages.Dutch,      "Unrecognized Terminal Argument"), "Niet-herkend terminalargument"},
                {(Languages.Polish,     "Unrecognized Terminal Argument"), "Nierozpoznany argument terminala"},
                {(Languages.Turkish,    "Unrecognized Terminal Argument"), "Tanınmayan terminal bağımsız değişkeni"},
                {(Languages.Vietnamese, "Unrecognized Terminal Argument"), "Đối số đầu cuối không được nhận dạng"},
                {(Languages.Indonesian, "Unrecognized Terminal Argument"), "Argumen terminal tidak dikenali"},
                {(Languages.Czech,      "Unrecognized Terminal Argument"), "Neznámý argument terminálu"},
                {(Languages.Korean,     "Unrecognized Terminal Argument"), "인식할 수 없는 터미널 인수"},
                {(Languages.Ukrainian,  "Unrecognized Terminal Argument"), "Нерозпізнаний аргумент терміналу"},
                {(Languages.Arabic,     "Unrecognized Terminal Argument"), "وسيطة طرفية غير معروفة"},
                {(Languages.Swedish,    "Unrecognized Terminal Argument"), "Okänt terminalargument"},
                {(Languages.Persian,    "Unrecognized Terminal Argument"), "آرگومان ترمینال نامشخص"},
                {(Languages.Chinese,    "Unrecognized Terminal Argument"), "无法识别的终端参数"},

                // No Language Provided
                {(Languages.English_UK, "No Language Provided"), "No Language Provided"},
                {(Languages.English_US, "No Language Provided"), "No Language Provided"},
                {(Languages.Spanish,    "No Language Provided"), "No se proporcionó ningún idioma"},
                {(Languages.German,     "No Language Provided"), "Keine Sprache angegeben"},
                {(Languages.French,     "No Language Provided"), "Aucune langue fournie"},
                {(Languages.Portuguese, "No Language Provided"), "Nenhum idioma fornecido"},
                {(Languages.Russian,    "No Language Provided"), "Язык не указан"},
                {(Languages.Italian,    "No Language Provided"), "Nessuna lingua fornita"},
                {(Languages.Dutch,      "No Language Provided"), "Geen taal opgegeven"},
                {(Languages.Polish,     "No Language Provided"), "Nie podano języka"},
                {(Languages.Turkish,    "No Language Provided"), "Dil sağlanmadı"},
                {(Languages.Vietnamese, "No Language Provided"), "Không cung cấp ngôn ngữ"},
                {(Languages.Indonesian, "No Language Provided"), "Bahasa tidak disediakan"},
                {(Languages.Czech,      "No Language Provided"), "Nebyl zadán žádný jazyk"},
                {(Languages.Korean,     "No Language Provided"), "언어가 제공되지 않았습니다"},
                {(Languages.Ukrainian,  "No Language Provided"), "Мову не вказано"},
                {(Languages.Arabic,     "No Language Provided"), "لم يتم تقديم أي لغة"},
                {(Languages.Swedish,    "No Language Provided"), "Inget språk angivet"},
                {(Languages.Persian,    "No Language Provided"), "زبانی ارائه نشده است"},
                {(Languages.Chinese,    "No Language Provided"), "未提供语言"},

                // Invalid Language Provided
                {(Languages.English_UK, "Invalid Language Provided"), "Invalid Language Provided"},
                {(Languages.English_US, "Invalid Language Provided"), "Invalid Language Provided"},
                {(Languages.Spanish,    "Invalid Language Provided"), "Idioma proporcionado no válido"},
                {(Languages.German,     "Invalid Language Provided"), "Ungültige Sprache angegeben"},
                {(Languages.French,     "Invalid Language Provided"), "Langue fournie non valide"},
                {(Languages.Portuguese, "Invalid Language Provided"), "Idioma fornecido inválido"},
                {(Languages.Russian,    "Invalid Language Provided"), "Указан недопустимый язык"},
                {(Languages.Italian,    "Invalid Language Provided"), "Lingua fornita non valida"},
                {(Languages.Dutch,      "Invalid Language Provided"), "Ongeldige taal opgegeven"},
                {(Languages.Polish,     "Invalid Language Provided"), "Podano nieprawidłowy język"},
                {(Languages.Turkish,    "Invalid Language Provided"), "Geçersiz dil sağlandı"},
                {(Languages.Vietnamese, "Invalid Language Provided"), "Ngôn ngữ được cung cấp không hợp lệ"},
                {(Languages.Indonesian, "Invalid Language Provided"), "Bahasa yang diberikan tidak valid"},
                {(Languages.Czech,      "Invalid Language Provided"), "Byl zadán neplatný jazyk"},
                {(Languages.Korean,     "Invalid Language Provided"), "잘못된 언어가 제공되었습니다"},
                {(Languages.Ukrainian,  "Invalid Language Provided"), "Надавана мова недійсна"},
                {(Languages.Arabic,     "Invalid Language Provided"), "تم تقديم لغة غير صالحة"},
                {(Languages.Swedish,    "Invalid Language Provided"), "Ogiltigt språk angivet"},
                {(Languages.Persian,    "Invalid Language Provided"), "زبان نامعتبری ارائه شده است"},
                {(Languages.Chinese,    "Invalid Language Provided"), "提供的语言无效"},

                // Entrypoint Source Assembly File
                {(Languages.English_UK, "Entrypoint Source Assembly File"), "Entrypoint Source Assembly File"},
                {(Languages.English_US, "Entrypoint Source Assembly File"), "Entrypoint Source Assembly File"},
                {(Languages.Spanish,    "Entrypoint Source Assembly File"), "Archivo fuente de ensamblador del punto de entrada"},
                {(Languages.German,     "Entrypoint Source Assembly File"), "Quell-Assembly-Datei des Einstiegspunkts"},
                {(Languages.French,     "Entrypoint Source Assembly File"), "Fichier source d'assemblage du point d'entrée"},
                {(Languages.Portuguese, "Entrypoint Source Assembly File"), "Arquivo fonte de montagem do ponto de entrada"},
                {(Languages.Russian,    "Entrypoint Source Assembly File"), "Исходный файл ассемблера точки входа"},
                {(Languages.Italian,    "Entrypoint Source Assembly File"), "File sorgente assembly del punto di ingresso"},
                {(Languages.Dutch,      "Entrypoint Source Assembly File"), "Entrypoint bronassemblybestand"},
                {(Languages.Polish,     "Entrypoint Source Assembly File"), "Plik źródłowy asemblera punktu wejścia"},
                {(Languages.Turkish,    "Entrypoint Source Assembly File"), "Giriş noktası kaynak montaj dosyası"},
                {(Languages.Vietnamese, "Entrypoint Source Assembly File"), "Tệp nguồn hợp ngữ điểm vào"},
                {(Languages.Indonesian, "Entrypoint Source Assembly File"), "File assembly sumber titik masuk"},
                {(Languages.Czech,      "Entrypoint Source Assembly File"), "Zdrojový soubor assembleru vstupního bodu"},
                {(Languages.Korean,     "Entrypoint Source Assembly File"), "진입점 소스 어셈블리 파일"},
                {(Languages.Ukrainian,  "Entrypoint Source Assembly File"), "Вхідний вихідний файл асемблера"},
                {(Languages.Arabic,     "Entrypoint Source Assembly File"), "ملف التجميع المصدر لنقطة الدخول"},
                {(Languages.Swedish,    "Entrypoint Source Assembly File"), "Entrypoint källassemblerfil"},
                {(Languages.Persian,    "Entrypoint Source Assembly File"), "فایل منبع اسمبلی نقطه ورود"},
                {(Languages.Chinese,    "Entrypoint Source Assembly File"), "入口点源汇编文件"},

                // Output ROM/Disk Binary Output
                {(Languages.English_UK, "Output ROM/Disk Binary Output"), "Output ROM/Disk Binary Output"},
                {(Languages.English_US, "Output ROM/Disk Binary Output"), "Output ROM/Disk Binary Output"},
                {(Languages.Spanish,    "Output ROM/Disk Binary Output"), "Salida binaria de ROM/disco"},
                {(Languages.German,     "Output ROM/Disk Binary Output"), "Ausgabe ROM/Disk Binärdatei"},
                {(Languages.French,     "Output ROM/Disk Binary Output"), "Sortie binaire ROM/disque"},
                {(Languages.Portuguese, "Output ROM/Disk Binary Output"), "Saída binária de ROM/Disco"},
                {(Languages.Russian,    "Output ROM/Disk Binary Output"), "Выходной бинарный файл ROM/диска"},
                {(Languages.Italian,    "Output ROM/Disk Binary Output"), "Output binario ROM/disco"},
                {(Languages.Dutch,      "Output ROM/Disk Binary Output"), "Uitvoer ROM/schijf binair bestand"},
                {(Languages.Polish,     "Output ROM/Disk Binary Output"), "Wynik binarny ROM/dysku"},
                {(Languages.Turkish,    "Output ROM/Disk Binary Output"), "Çıktı ROM/Disk İkili Çıktı"},
                {(Languages.Vietnamese, "Output ROM/Disk Binary Output"), "Đầu ra nhị phân ROM/đĩa"},
                {(Languages.Indonesian, "Output ROM/Disk Binary Output"), "Output biner ROM/Disk"},
                {(Languages.Czech,      "Output ROM/Disk Binary Output"), "Výstupní binární soubor ROM/disku"},
                {(Languages.Korean,     "Output ROM/Disk Binary Output"), "출력 ROM/디스크 바이너리 출력"},
                {(Languages.Ukrainian,  "Output ROM/Disk Binary Output"), "Вихід ROM/дисковий бінарний файл"},
                {(Languages.Arabic,     "Output ROM/Disk Binary Output"), "إخراج ثنائي للـ ROM/القرص"},
                {(Languages.Swedish,    "Output ROM/Disk Binary Output"), "Utdata ROM/Disk binär utdata"},
                {(Languages.Persian,    "Output ROM/Disk Binary Output"), "خروجی دودویی ROM/دیسک"},
                {(Languages.Chinese,    "Output ROM/Disk Binary Output"), "输出ROM/磁盘二进制输出"},

                // Display the help string (you did that)
                {(Languages.English_UK, "Display the help string (you did that)"), "Display the help string (you did that)"},
                {(Languages.English_US, "Display the help string (you did that)"), "Display the help string (you did that)"},
                {(Languages.Spanish,    "Display the help string (you did that)"), "Mostrar la cadena de ayuda (ya lo hiciste)"},
                {(Languages.German,     "Display the help string (you did that)"), "Hilfetext anzeigen (das hast du gemacht)"},
                {(Languages.French,     "Display the help string (you did that)"), "Afficher la chaîne d'aide (tu l'as fait)"},
                {(Languages.Portuguese, "Display the help string (you did that)"), "Exibir a string de ajuda (você fez isso)"},
                {(Languages.Russian,    "Display the help string (you did that)"), "Показать строку помощи (ты это сделал)"},
                {(Languages.Italian,    "Display the help string (you did that)"), "Mostra la stringa di aiuto (lo hai fatto)"},
                {(Languages.Dutch,      "Display the help string (you did that)"), "Helpstring weergeven (dat heb je gedaan)"},
                {(Languages.Polish,     "Display the help string (you did that)"), "Wyświetl ciąg pomocy (zrobiłeś to)"},
                {(Languages.Turkish,    "Display the help string (you did that)"), "Yardım dizesini göster (bunu yaptın)"},
                {(Languages.Vietnamese, "Display the help string (you did that)"), "Hiển thị chuỗi trợ giúp (bạn đã làm điều đó)"},
                {(Languages.Indonesian, "Display the help string (you did that)"), "Tampilkan string bantuan (kamu sudah melakukannya)"},
                {(Languages.Czech,      "Display the help string (you did that)"), "Zobrazit pomocný řetězec (udělal jsi to)"},
                {(Languages.Korean,     "Display the help string (you did that)"), "도움말 문자열 표시 (너가 했어)"},
                {(Languages.Ukrainian,  "Display the help string (you did that)"), "Показати рядок допомоги (ти це зробив)"},
                {(Languages.Arabic,     "Display the help string (you did that)"), "عرض سلسلة المساعدة (لقد فعلت ذلك)"},
                {(Languages.Swedish,    "Display the help string (you did that)"), "Visa hjälptsträng (du gjorde det)"},
                {(Languages.Persian,    "Display the help string (you did that)"), "نمایش رشته راهنما (شما انجام دادید)"},
                {(Languages.Chinese,    "Display the help string (you did that)"), "显示帮助字符串（你做到了）"},

                // Choose a language to use
                {(Languages.English_UK, "Choose a language to use"), "Choose a language to use"},
                {(Languages.English_US, "Choose a language to use"), "Choose a language to use"},
                {(Languages.Spanish,    "Choose a language to use"), "Elige un idioma para usar"},
                {(Languages.German,     "Choose a language to use"), "Wähle eine Sprache zur Verwendung"},
                {(Languages.French,     "Choose a language to use"), "Choisissez une langue à utiliser"},
                {(Languages.Portuguese, "Choose a language to use"), "Escolha um idioma para usar"},
                {(Languages.Russian,    "Choose a language to use"), "Выберите язык для использования"},
                {(Languages.Italian,    "Choose a language to use"), "Scegli una lingua da usare"},
                {(Languages.Dutch,      "Choose a language to use"), "Kies een taal om te gebruiken"},
                {(Languages.Polish,     "Choose a language to use"), "Wybierz język do użycia"},
                {(Languages.Turkish,    "Choose a language to use"), "Kullanmak için bir dil seçin"},
                {(Languages.Vietnamese, "Choose a language to use"), "Chọn một ngôn ngữ để sử dụng"},
                {(Languages.Indonesian, "Choose a language to use"), "Pilih bahasa yang akan digunakan"},
                {(Languages.Czech,      "Choose a language to use"), "Vyberte jazyk k použití"},
                {(Languages.Korean,     "Choose a language to use"), "사용할 언어를 선택하세요"},
                {(Languages.Ukrainian,  "Choose a language to use"), "Виберіть мову для використання"},
                {(Languages.Arabic,     "Choose a language to use"), "اختر لغة للاستخدام"},
                {(Languages.Swedish,    "Choose a language to use"), "Välj ett språk att använda"},
                {(Languages.Persian,    "Choose a language to use"), "یک زبان برای استفاده انتخاب کنید"},
                {(Languages.Chinese,    "Choose a language to use"), "选择要使用的语言"},

                // Display all Languages
                {(Languages.English_UK, "Display all Languages"), "Display all Languages"},
                {(Languages.English_US, "Display all Languages"), "Display all Languages"},
                {(Languages.Spanish,    "Display all Languages"), "Mostrar todos los idiomas"},
                {(Languages.German,     "Display all Languages"), "Alle Sprachen anzeigen"},
                {(Languages.French,     "Display all Languages"), "Afficher toutes les langues"},
                {(Languages.Portuguese, "Display all Languages"), "Exibir todos os idiomas"},
                {(Languages.Russian,    "Display all Languages"), "Показать все языки"},
                {(Languages.Italian,    "Display all Languages"), "Mostra tutte le lingue"},
                {(Languages.Dutch,      "Display all Languages"), "Toon alle talen"},
                {(Languages.Polish,     "Display all Languages"), "Wyświetl wszystkie języki"},
                {(Languages.Turkish,    "Display all Languages"), "Tüm dilleri göster"},
                {(Languages.Vietnamese, "Display all Languages"), "Hiển thị tất cả các ngôn ngữ"},
                {(Languages.Indonesian, "Display all Languages"), "Tampilkan semua bahasa"},
                {(Languages.Czech,      "Display all Languages"), "Zobrazit všechny jazyky"},
                {(Languages.Korean,     "Display all Languages"), "모든 언어 표시"},
                {(Languages.Ukrainian,  "Display all Languages"), "Показати всі мови"},
                {(Languages.Arabic,     "Display all Languages"), "عرض جميع اللغات"},
                {(Languages.Swedish,    "Display all Languages"), "Visa alla språk"},
                {(Languages.Persian,    "Display all Languages"), "نمایش همه زبان‌ها"},
                {(Languages.Chinese,    "Display all Languages"), "显示所有语言"},

                // Brackets may only contain one term
                {(Languages.English_UK, "Brackets may only contain one term"), "Brackets may only contain one term"},
                {(Languages.English_US, "Brackets may only contain one term"), "Brackets may only contain one term"},
                {(Languages.Spanish,    "Brackets may only contain one term"), "Los paréntesis solo pueden contener un término"},
                {(Languages.German,     "Brackets may only contain one term"), "Klammern dürfen nur einen Term enthalten"},
                {(Languages.French,     "Brackets may only contain one term"), "Les parenthèses ne peuvent contenir qu’un seul terme"},
                {(Languages.Portuguese, "Brackets may only contain one term"), "Parênteses podem conter apenas um termo"},
                {(Languages.Russian,    "Brackets may only contain one term"), "Скобки могут содержать только один термин"},
                {(Languages.Italian,    "Brackets may only contain one term"), "Le parentesi possono contenere solo un termine"},
                {(Languages.Dutch,      "Brackets may only contain one term"), "Haakjes mogen slechts één term bevatten"},
                {(Languages.Polish,     "Brackets may only contain one term"), "Nawiasy mogą zawierać tylko jeden wyraz"},
                {(Languages.Turkish,    "Brackets may only contain one term"), "Parantezler yalnızca bir terim içerebilir"},
                {(Languages.Vietnamese, "Brackets may only contain one term"), "Dấu ngoặc chỉ được chứa một thuật ngữ"},
                {(Languages.Indonesian, "Brackets may only contain one term"), "Tanda kurung hanya boleh berisi satu istilah"},
                {(Languages.Czech,      "Brackets may only contain one term"), "Závorky mohou obsahovat pouze jeden výraz"},
                {(Languages.Korean,     "Brackets may only contain one term"), "괄호에는 항 하나만 포함될 수 있습니다"},
                {(Languages.Ukrainian,  "Brackets may only contain one term"), "Дужки можуть містити лише один термін"},
                {(Languages.Arabic,     "Brackets may only contain one term"), "يمكن أن تحتوي الأقواس على مصطلح واحد فقط"},
                {(Languages.Swedish,    "Brackets may only contain one term"), "Parenteser får bara innehålla en term"},
                {(Languages.Persian,    "Brackets may only contain one term"), "براکت‌ها تنها می‌توانند شامل یک عبارت باشند"},
                {(Languages.Chinese,    "Brackets may only contain one term"), "括号内只能包含一个术语"},
            
                // Unexpected Comma, the amount of terms to resolve is
                {(Languages.English_UK, "Unexpected Comma, the amount of terms to resolve is"), "Unexpected Comma, the amount of terms to resolve is"},
                {(Languages.English_US, "Unexpected Comma, the amount of terms to resolve is"), "Unexpected Comma, the amount of terms to resolve is"},
                {(Languages.Spanish,    "Unexpected Comma, the amount of terms to resolve is"), "Coma inesperada, la cantidad de términos a resolver es"},
                {(Languages.German,     "Unexpected Comma, the amount of terms to resolve is"), "Unerwartetes Komma, die Anzahl der zu lösenden Terme ist"},
                {(Languages.French,     "Unexpected Comma, the amount of terms to resolve is"), "Virgule inattendue, le nombre de termes à résoudre est"},
                {(Languages.Portuguese, "Unexpected Comma, the amount of terms to resolve is"), "Vírgula inesperada, a quantidade de termos a resolver é"},
                {(Languages.Russian,    "Unexpected Comma, the amount of terms to resolve is"), "Неожиданная запятая, количество выражений для разрешения:"},
                {(Languages.Italian,    "Unexpected Comma, the amount of terms to resolve is"), "Virgola imprevista, il numero di termini da risolvere è"},
                {(Languages.Dutch,      "Unexpected Comma, the amount of terms to resolve is"), "Onverwachte komma, het aantal op te lossen termen is"},
                {(Languages.Polish,     "Unexpected Comma, the amount of terms to resolve is"), "Nieoczekiwany przecinek, liczba wyrażeń do rozwiązania to"},
                {(Languages.Turkish,    "Unexpected Comma, the amount of terms to resolve is"), "Beklenmeyen virgül, çözülecek terim sayısı"},
                {(Languages.Vietnamese, "Unexpected Comma, the amount of terms to resolve is"), "Dấu phẩy không mong đợi, số lượng thuật ngữ cần giải quyết là"},
                {(Languages.Indonesian, "Unexpected Comma, the amount of terms to resolve is"), "Koma tak terduga, jumlah istilah yang harus diselesaikan adalah"},
                {(Languages.Czech,      "Unexpected Comma, the amount of terms to resolve is"), "Neočekávaná čárka, počet výrazů k vyřešení je"},
                {(Languages.Korean,     "Unexpected Comma, the amount of terms to resolve is"), "예상치 못한 쉼표, 해결할 항 수는"},
                {(Languages.Ukrainian,  "Unexpected Comma, the amount of terms to resolve is"), "Неочікувана кома, кількість термів для обробки:"},
                {(Languages.Arabic,     "Unexpected Comma, the amount of terms to resolve is"), "فاصلة غير متوقعة، عدد المصطلحات المطلوب حلها هو"},
                {(Languages.Swedish,    "Unexpected Comma, the amount of terms to resolve is"), "Oväntat komma, antal termer att lösa är"},
                {(Languages.Persian,    "Unexpected Comma, the amount of terms to resolve is"), "ویرگول غیرمنتظره، تعداد عبارت‌هایی که باید حل شوند:"},
                {(Languages.Chinese,    "Unexpected Comma, the amount of terms to resolve is"), "意外的逗号，需要解析的项数是"},

                // Terms left unaccounted for
                {(Languages.English_UK, "Terms left unaccounted for"), "Terms left unaccounted for"},
                {(Languages.English_US, "Terms left unaccounted for"), "Terms left unaccounted for"},
                {(Languages.Spanish,    "Terms left unaccounted for"), "Términos no contabilizados"},
                {(Languages.German,     "Terms left unaccounted for"), "Nicht berücksichtigte Terme"},
                {(Languages.French,     "Terms left unaccounted for"), "Termes non pris en compte"},
                {(Languages.Portuguese, "Terms left unaccounted for"), "Termos não contabilizados"},
                {(Languages.Russian,    "Terms left unaccounted for"), "Невучтённые выражения"},
                {(Languages.Italian,    "Terms left unaccounted for"), "Termini non considerati"},
                {(Languages.Dutch,      "Terms left unaccounted for"), "Niet meegerekende termen"},
                {(Languages.Polish,     "Terms left unaccounted for"), "Nierozliczone wyrazy"},
                {(Languages.Turkish,    "Terms left unaccounted for"), "Hesaba katılmamış terimler"},
                {(Languages.Vietnamese, "Terms left unaccounted for"), "Thuật ngữ chưa được tính đến"},
                {(Languages.Indonesian, "Terms left unaccounted for"), "Istilah yang belum diperhitungkan"},
                {(Languages.Czech,      "Terms left unaccounted for"), "Nevyúčtované výrazy"},
                {(Languages.Korean,     "Terms left unaccounted for"), "계산되지 않은 항"},
                {(Languages.Ukrainian,  "Terms left unaccounted for"), "Невраховані терміни"},
                {(Languages.Arabic,     "Terms left unaccounted for"), "مصطلحات غير محسوبة"},
                {(Languages.Swedish,    "Terms left unaccounted for"), "Termer som inte redovisats"},
                {(Languages.Persian,    "Terms left unaccounted for"), "عبارت‌های در نظر گرفته‌نشده"},
                {(Languages.Chinese,    "Terms left unaccounted for"), "未计入的项"},
            };

            internal static readonly Dictionary<(Languages, DecodingPhases), string> DecodePhaseMessages = new() {
                // === Terminal Interaction Phase ===
                {(Languages.English_UK,     DecodingPhases.TERMINAL), "Terminal Interaction Phase"},
                {(Languages.English_US,     DecodingPhases.TERMINAL), "Terminal Interaction Phase"},
                {(Languages.Spanish,        DecodingPhases.TERMINAL), "Fase de interacción con el terminal"},
                {(Languages.German,         DecodingPhases.TERMINAL), "Terminal-Interaktionsphase"},
                {(Languages.French,         DecodingPhases.TERMINAL), "Phase d'interaction terminale"},
                {(Languages.Portuguese,     DecodingPhases.TERMINAL), "Fase de interação com o terminal"},
                {(Languages.Russian,        DecodingPhases.TERMINAL), "Фаза взаимодействия с терминалом"},
                {(Languages.Italian,        DecodingPhases.TERMINAL), "Fase di interazione con il terminale"},
                {(Languages.Dutch,          DecodingPhases.TERMINAL), "Terminal-interactiefase"},
                {(Languages.Polish,         DecodingPhases.TERMINAL), "Faza interakcji z terminalem"},
                {(Languages.Turkish,        DecodingPhases.TERMINAL), "Terminal etkileşim aşaması"},
                {(Languages.Vietnamese,     DecodingPhases.TERMINAL), "Giai đoạn tương tác thiết bị đầu cuối"},
                {(Languages.Indonesian,     DecodingPhases.TERMINAL), "Fase interaksi terminal"},
                {(Languages.Czech,          DecodingPhases.TERMINAL), "Fáze interakce s terminálem"},
                {(Languages.Korean,         DecodingPhases.TERMINAL), "터미널 상호 작용 단계"},
                {(Languages.Ukrainian,      DecodingPhases.TERMINAL), "Фаза взаємодії з терміналом"},
                {(Languages.Arabic,         DecodingPhases.TERMINAL), "مرحلة التفاعل مع الطرفية"},
                {(Languages.Swedish,        DecodingPhases.TERMINAL), "Terminalinteraktionsfas"},
                {(Languages.Persian,        DecodingPhases.TERMINAL), "مرحله تعامل با ترمینال"},
                {(Languages.Chinese,        DecodingPhases.TERMINAL), "终端交互阶段"},

                // === Token Decoding Phase ===
                {(Languages.English_UK,     DecodingPhases.TOKEN),    "Token Decoding Phase"},
                {(Languages.English_US,     DecodingPhases.TOKEN),    "Token Decoding Phase"},
                {(Languages.Spanish,        DecodingPhases.TOKEN),    "Fase de decodificación de tokens"},
                {(Languages.German,         DecodingPhases.TOKEN),    "Token-Dekodierungsphase"},
                {(Languages.French,         DecodingPhases.TOKEN),    "Phase de décodage des jetons"},
                {(Languages.Portuguese,     DecodingPhases.TOKEN),    "Fase de decodificação de tokens"},
                {(Languages.Russian,        DecodingPhases.TOKEN),    "Фаза декодирования токенов"},
                {(Languages.Italian,        DecodingPhases.TOKEN),    "Fase di decodifica dei token"},
                {(Languages.Dutch,          DecodingPhases.TOKEN),    "Token-decoderingfase"},
                {(Languages.Polish,         DecodingPhases.TOKEN),    "Faza dekodowania tokenów"},
                {(Languages.Turkish,        DecodingPhases.TOKEN),    "Token çözümleme aşaması"},
                {(Languages.Vietnamese,     DecodingPhases.TOKEN),    "Giai đoạn giải mã token"},
                {(Languages.Indonesian,     DecodingPhases.TOKEN),    "Fase dekripsi token"},
                {(Languages.Czech,          DecodingPhases.TOKEN),    "Fáze dekódování tokenů"},
                {(Languages.Korean,         DecodingPhases.TOKEN),    "토큰 디코딩 단계"},
                {(Languages.Ukrainian,      DecodingPhases.TOKEN),    "Фаза декодування токенів"},
                {(Languages.Arabic,         DecodingPhases.TOKEN),    "مرحلة فك تشفير الرموز"},
                {(Languages.Swedish,        DecodingPhases.TOKEN),    "Fas för avkodning av token"},
                {(Languages.Persian,        DecodingPhases.TOKEN),    "مرحله رمزگشایی توکن"},
                {(Languages.Chinese,        DecodingPhases.TOKEN),    "标记解码阶段"},
                
                {(Languages.English_UK,     DecodingPhases.LINKER_INIT),    "Linker Initialisation Phase"},
                {(Languages.English_US,     DecodingPhases.LINKER_INIT),    "Linker Initialization Phase"},
                {(Languages.Spanish,        DecodingPhases.LINKER_INIT),    "Fase de inicialización del enlazador"},
                {(Languages.German,         DecodingPhases.LINKER_INIT),    "Linker-Initialisierungsphase"},
                {(Languages.French,         DecodingPhases.LINKER_INIT),    "Phase d’initialisation de l’éditeur de liens"},
                {(Languages.Portuguese,     DecodingPhases.LINKER_INIT),    "Fase de inicialização do ligador"},
                {(Languages.Russian,        DecodingPhases.LINKER_INIT),    "Фаза инициализации компоновщика"},
                {(Languages.Italian,        DecodingPhases.LINKER_INIT),    "Fase di inizializzazione del linker"},
                {(Languages.Dutch,          DecodingPhases.LINKER_INIT),    "Linker-initialisatiefase"},
                {(Languages.Polish,         DecodingPhases.LINKER_INIT),    "Faza inicjalizacji łączycza"},
                {(Languages.Turkish,        DecodingPhases.LINKER_INIT),    "Bağlayıcı başlatma aşaması"},
                {(Languages.Vietnamese,     DecodingPhases.LINKER_INIT),    "Giai đoạn khởi tạo liên kết"},
                {(Languages.Indonesian,     DecodingPhases.LINKER_INIT),    "Fase inisialisasi linker"},
                {(Languages.Czech,          DecodingPhases.LINKER_INIT),    "Fáze inicializace linkeru"},
                {(Languages.Korean,         DecodingPhases.LINKER_INIT),    "링커 초기화 단계"},
                {(Languages.Ukrainian,      DecodingPhases.LINKER_INIT),    "Фаза ініціалізації зв’язування"},
                {(Languages.Arabic,         DecodingPhases.LINKER_INIT),    "مرحلة تهيئة الرابط"},
                {(Languages.Swedish,        DecodingPhases.LINKER_INIT),    "Länkarinitieringsfas"},
                {(Languages.Persian,        DecodingPhases.LINKER_INIT),    "مرحله‌ی راه‌اندازی لینک‌گر"},
                {(Languages.Chinese,        DecodingPhases.LINKER_INIT),    "链接器初始化阶段"},
            };


            internal static readonly Dictionary<(Languages, ErrorTypes), string> ErrorTypeMessages  = new() {
                // Syntax Error
                {(Languages.English_UK,     ErrorTypes.SyntaxError), "Syntax Error"},
                {(Languages.English_US,     ErrorTypes.SyntaxError), "Syntax Error"},
                {(Languages.Spanish,        ErrorTypes.SyntaxError), "Error de sintaxis"},
                {(Languages.German,         ErrorTypes.SyntaxError), "Syntaxfehler"},
                {(Languages.Japanese,       ErrorTypes.SyntaxError), "構文エラー"},
                {(Languages.French,         ErrorTypes.SyntaxError), "Erreur de syntaxe"},
                {(Languages.Portuguese,     ErrorTypes.SyntaxError), "Erro de sintaxe"},
                {(Languages.Russian,        ErrorTypes.SyntaxError), "Синтаксическая ошибка"},
                {(Languages.Italian,        ErrorTypes.SyntaxError), "Errore di sintassi"},
                {(Languages.Dutch,          ErrorTypes.SyntaxError), "Syntaxfout"},
                {(Languages.Polish,         ErrorTypes.SyntaxError), "Błąd składni"},
                {(Languages.Turkish,        ErrorTypes.SyntaxError), "Sözdizimi hatası"},
                {(Languages.Vietnamese,     ErrorTypes.SyntaxError), "Lỗi cú pháp"},
                {(Languages.Indonesian,     ErrorTypes.SyntaxError), "Kesalahan sintaksis"},
                {(Languages.Czech,          ErrorTypes.SyntaxError), "Chyba syntaxe"},
                {(Languages.Korean,         ErrorTypes.SyntaxError), "구문 오류"},
                {(Languages.Ukrainian,      ErrorTypes.SyntaxError), "Синтаксична помилка"},
                {(Languages.Arabic,         ErrorTypes.SyntaxError), "خطأ في بناء الجملة"},
                {(Languages.Swedish,        ErrorTypes.SyntaxError), "Syntaxfel"},
                {(Languages.Persian,        ErrorTypes.SyntaxError), "خطای نحو"},
                {(Languages.Chinese,        ErrorTypes.SyntaxError), "语法错误"},

                // Parsing Error
                {(Languages.English_UK,     ErrorTypes.ParsingError), "Parsing Error"},
                {(Languages.English_US,     ErrorTypes.ParsingError), "Parsing Error"},
                {(Languages.Spanish,        ErrorTypes.ParsingError), "Error de análisis"},
                {(Languages.German,         ErrorTypes.ParsingError), "Analysefehler"},
                {(Languages.Japanese,       ErrorTypes.ParsingError), "解析エラー"},
                {(Languages.French,         ErrorTypes.ParsingError), "Erreur d'analyse"},
                {(Languages.Portuguese,     ErrorTypes.ParsingError), "Erro de análise"},
                {(Languages.Russian,        ErrorTypes.ParsingError), "Ошибка анализа"},
                {(Languages.Italian,        ErrorTypes.ParsingError), "Errore di analisi"},
                {(Languages.Dutch,          ErrorTypes.ParsingError), "Parsefout"},
                {(Languages.Polish,         ErrorTypes.ParsingError), "Błąd parsowania"},
                {(Languages.Turkish,        ErrorTypes.ParsingError), "Ayrıştırma hatası"},
                {(Languages.Vietnamese,     ErrorTypes.ParsingError), "Lỗi phân tích"},
                {(Languages.Indonesian,     ErrorTypes.ParsingError), "Kesalahan parsing"},
                {(Languages.Czech,          ErrorTypes.ParsingError), "Chyba analýzy"},
                {(Languages.Korean,         ErrorTypes.ParsingError), "파싱 오류"},
                {(Languages.Ukrainian,      ErrorTypes.ParsingError), "Помилка розбору"},
                {(Languages.Arabic,         ErrorTypes.ParsingError), "خطأ في التحليل"},
                {(Languages.Swedish,        ErrorTypes.ParsingError), "Parsningsfel"},
                {(Languages.Persian,        ErrorTypes.ParsingError), "خطای تجزیه"},
                {(Languages.Chinese,        ErrorTypes.ParsingError), "解析错误"},
                
                {(Languages.English_UK,   ErrorTypes.LinkerError), "Linker Error"},
                {(Languages.English_US,   ErrorTypes.LinkerError), "Linker Error"},
                {(Languages.Spanish,      ErrorTypes.LinkerError), "Error de vinculación"},
                {(Languages.German,       ErrorTypes.LinkerError), "Linker-Fehler"},
                {(Languages.Japanese,     ErrorTypes.LinkerError), "リンカ・エラー"},
                {(Languages.French,       ErrorTypes.LinkerError), "Erreur de l’éditeur de liens"},
                {(Languages.Portuguese,   ErrorTypes.LinkerError), "Erro do ligador"},
                {(Languages.Russian,      ErrorTypes.LinkerError), "Ошибка компоновки"},
                {(Languages.Italian,      ErrorTypes.LinkerError), "Errore del linker"},
                {(Languages.Dutch,        ErrorTypes.LinkerError), "Linker-fout"},
                {(Languages.Polish,       ErrorTypes.LinkerError), "Błąd linkowania"},
                {(Languages.Turkish,      ErrorTypes.LinkerError), "Bağlayıcı hatası"},
                {(Languages.Vietnamese,   ErrorTypes.LinkerError), "Lỗi liên kết"},
                {(Languages.Indonesian,   ErrorTypes.LinkerError), "Kesalahan linker"},
                {(Languages.Czech,        ErrorTypes.LinkerError), "Chyba linkeru"},
                {(Languages.Korean,       ErrorTypes.LinkerError), "링커 오류"},
                {(Languages.Ukrainian,    ErrorTypes.LinkerError), "Помилка зв’язування"},
                {(Languages.Arabic,       ErrorTypes.LinkerError), "خطأ فى الرابط"},
                {(Languages.Swedish,      ErrorTypes.LinkerError), "Länkningsfel"},
                {(Languages.Persian,      ErrorTypes.LinkerError), "خطای لینک‌گر"},
                {(Languages.Chinese,      ErrorTypes.LinkerError), "链接器错误"},

                // Nothing To Do
                {(Languages.English_UK,     ErrorTypes.NothingToDo), "Nothing to do"},
                {(Languages.English_US,     ErrorTypes.NothingToDo), "Nothing to do"},
                {(Languages.Spanish,        ErrorTypes.NothingToDo), "Nada que hacer"},
                {(Languages.German,         ErrorTypes.NothingToDo), "Nichts zu tun"},
                {(Languages.Japanese,       ErrorTypes.NothingToDo), "やることなし"},
                {(Languages.French,         ErrorTypes.NothingToDo), "Rien à faire"},
                {(Languages.Portuguese,     ErrorTypes.NothingToDo), "Nada a fazer"},
                {(Languages.Russian,        ErrorTypes.NothingToDo), "Нечего делать"},
                {(Languages.Italian,        ErrorTypes.NothingToDo), "Niente da fare"},
                {(Languages.Dutch,          ErrorTypes.NothingToDo), "Niets te doen"},
                {(Languages.Polish,         ErrorTypes.NothingToDo), "Nie ma nic do zrobienia"},
                {(Languages.Turkish,        ErrorTypes.NothingToDo), "Yapılacak bir şey yok"},
                {(Languages.Vietnamese,     ErrorTypes.NothingToDo), "Không có gì để làm"},
                {(Languages.Indonesian,     ErrorTypes.NothingToDo), "Tidak ada yang perlu dilakukan"},
                {(Languages.Czech,          ErrorTypes.NothingToDo), "Není co dělat"},
                {(Languages.Korean,         ErrorTypes.NothingToDo), "할 일이 없습니다"},
                {(Languages.Ukrainian,      ErrorTypes.NothingToDo), "Робити нічого"},
                {(Languages.Arabic,         ErrorTypes.NothingToDo), "لا شيء للقيام به"},
                {(Languages.Swedish,        ErrorTypes.NothingToDo), "Inget att göra"},
                {(Languages.Persian,        ErrorTypes.NothingToDo), "کاری برای انجام نیست"},
                {(Languages.Chinese,        ErrorTypes.NothingToDo), "无需操作"},
            };
        }
    }
}
